In [7]:
import sqlite3
import pandas as pd


table = 'bronze_income_stmt_quarterly'

with sqlite3.connect('../data/tase_data_warehouse.db') as conn:
    df = pd.read_sql(f"SELECT * FROM {table} ", conn)

df['date'] = pd.to_datetime(df['report_date'], utc=True).dt.date

df['net_income_matrix'] = (df['Net Income'] / 1e9).round(2)
df['Revenue_matrix'] = (df['Total Revenue'] / 1e9).round(2)
df =df.rename(columns={'Diluted EPS': 'EPS_margin'}) 
df =df[['date','Revenue_matrix','net_income_matrix','EPS_margin','ticker']].sort_values(['ticker','date'], ascending=False)

df

          date  Revenue_matrix  net_income_matrix  EPS_margin   ticker
5   2026-03-31            5.51               2.12        1.62  POLI.TA
6   2025-12-31            5.15               2.08         NaN  POLI.TA
7   2025-09-30            6.70               2.76        2.09  POLI.TA
8   2025-06-30            6.44               2.54        1.92  POLI.TA
9   2025-03-31            5.69               2.42        1.83  POLI.TA
10  2024-12-31             NaN                NaN         NaN  POLI.TA
0   2026-03-31            5.41               2.35        1.58  LUMI.TA
1   2025-12-31            5.11               2.55        1.71  LUMI.TA
2   2025-09-30            5.87               2.70        1.81  LUMI.TA
3   2025-06-30            5.99               2.61        1.74  LUMI.TA
4   2025-03-31            5.38               2.40        1.60  LUMI.TA
16  2026-03-31            1.65               0.48        4.78  FIBI.TA
17  2025-12-31            1.30               0.51         NaN  FIBI.TA
18  2025-09-30            1.83               0.58        5.79  FIBI.TA
19  2025-06-30            1.84               0.64        6.35  FIBI.TA
20  2025-03-31            1.67               0.53        5.28  FIBI.TA
11  2026-03-31            3.12               0.93        0.76  DSCT.TA
12  2025-12-31            3.00               0.86         NaN  DSCT.TA
13  2025-09-30            3.38               1.13        0.92  DSCT.TA
14  2025-06-30            3.49               1.12        0.90  DSCT.TA
15  2025-03-31            3.25               1.04        0.84  DSCT.TA

In [8]:
import sqlite3
import pandas as pd


table = 'silver_balance_sheet_quarterly'

with sqlite3.connect('../data/tase_data_warehouse.db') as conn:
    df = pd.read_sql(f"SELECT * FROM {table} ", conn)

df.head()

         date  debt_to_equity_matrix  Stockholders Equity   ticker
0  2026-03-31                   0.66                65.55  POLI.TA
1  2025-12-31                   0.56                64.68  POLI.TA
2  2025-09-30                   0.52                63.74  POLI.TA
3  2025-06-30                   0.43                62.12  POLI.TA
4  2025-03-31                   0.41                60.22  POLI.TA